hack/e2e-test: Use uuidgen to create the cluster name
The old cluster-name extraction was leading to errors like [1]:

  error: error executing jsonpath "{ .items[].metadata.name }": array index out of bounds: index 0, length 0
  Creating ClusterDeployment Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
    template was:
      { .items[].metadata.name }
    object given to jsonpath engine was:
      map[string]interface {}{"kind":"List", "apiVersion":"v1", "metadata":map[string]interface {}{"selfLink":"", "resourceVersion":""}, "items":[]interface {}{}}-1
  Error from server (Invalid): Secret "Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:\n\ttemplate was:\n\t\t{ .items[].metadata.name }\n\tobject given to jsonpath engine was:\n\t\tmap[string]interface {}{\"kind\":\"List\", \"apiVersion\":\"v1\", \"metadata\":map[string]interface {}{\"selfLink\":\"\", \"resourceVersion\":\"\"}, \"items\":[]interface {}{}}-1-aws-creds" is invalid: [metadata.name: Invalid value: "Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:\n\ttemplate was:\n\t\t{ .items[].metadata.name }\n\tobject given to jsonpath engine was:\n\t\tmap[string]interface {}{\"kind\":\"List\", \"apiVersion\":\"v1\", \"metadata\":map[string]interface {}{\"selfLink\":\"\", \"resourceVersion\":\"\"}, \"items\":[]interface {}{}}-1-aws-creds": must be no more than 253 characters, metadata.name: Invalid value: "Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:\n\ttemplate was:\n\t\t{ .items[].metadata.name }\n\tobject given to jsonpath engine was:\n\t\tmap[string]interface {}{\"kind\":\"List\", \"apiVersion\":\"v1\", \"metadata\":map[string]interface {}{\"selfLink\":\"\", \"resourceVersion\":\"\"}, \"items\":[]interface {}{}}-1-aws-creds": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]

We don't actually need to match anything for our cluster names, so
just use a locally-generated UUID.

The cut avoids [2]:

  level=error msg="Error: module.vpc.aws_lb.api_internal: \"name\" cannot be longer than 32 characters: \"3948e3b5-0dcc-4f7d-8390-4795aa8d99f2-int\""

although there is installer work in progress to protect from "user
supplies long cluster name".

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_hive/222/pull-ci-openshift-hive-master-e2e/80/build-log.txt
[2]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_hive/222/pull-ci-openshift-hive-master-e2e/102/build-log.txt